channels:
  - rdkit
  - mordred-descriptor
  - schrodinger 
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12
  - certifi=2019.6.16
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icu=58.2
  - intel-openmp
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mordred=1.2.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - networkx=2.3
  - notebook=5.7.8
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - pixman=0.38.0
  - pmw=2.0.1
  - prometheus_client
  - prompt_toolkit=2.0.9
  - py-boost=1.67.0
  - pygments=2.4.2
  - pymol=2.3.3
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - rdkit=2019.03.3.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - statsmodels=0.10.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - asn1crypto==0.24.0
    - beautifulsoup4==4.7.1
    - biopandas==0.2.5
    - cffi==1.12.3
    - chardet==3.0.4
    - cryptography==2.7
    - easydict==1.9
    - gevent==1.4.0
    - gevent-openssl==1.2
    - greenlet==0.4.15
    - grequests==0.2.0
    - idna==2.8
    - ipymol==0.5
    - pycparser==2.19
    - pyopenssl==19.0.0
    - pypdb==1.200
    - requests==2.22.0
    - requests-cache==0.5.0
    - soupsieve==1.9.2
    - unittest2py3k==0.5.1
    - unittest2six==0.0.0
    - urllib3==1.25.3
    - xmltodict==0.12.0
